spring:
  application:
    name: account-service
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
          - metrics
          - info
  endpoint:
    health:
      show-details: never
      probes:
        enabled: true

logging:
  structured:
    format:
      console: ecs

account-service:
  cache:
    ttl-hours: 1
  dirty-flag:
    ttl-hours: 24